# Aplicación
spring.application.name=app-reparto-backend
server.port=8080

# Base de datos (PostgreSQL local con Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/appreparto
spring.datasource.username=appreparto
spring.datasource.password=appreparto123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=wwiCYY7mJh0gDGy001Jopg1yrh7QM9Bc/GM/QfIryJD9tgPur5rCY2BLrOGl77RM
app.jwt.expiration-ms=86400000

# AWS
aws.region=us-east-1
aws.s3.bucket-name=app-reparto-docs
aws.ses.from-email=noreply@appreparto.cl

# Tamaño máximo de archivos (fotos de facturas)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173
