/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  important: '#root',
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch / Material Design 3 tokens
        'primary':                '#00255a',
        'primary-container':      '#0f3b7e',
        'on-primary':             '#ffffff',
        'on-primary-container':   '#86a8f2',
        'primary-fixed':          '#d8e2ff',
        'primary-fixed-dim':      '#aec6ff',
        'secondary':              '#0051d5',
        'secondary-container':    '#316bf3',
        'on-secondary':           '#ffffff',
        'on-secondary-container': '#fefcff',
        'secondary-fixed':        '#dbe1ff',
        'secondary-fixed-dim':    '#b4c5ff',
        'tertiary':               '#002e1d',
        'tertiary-container':     '#00472f',
        'on-tertiary':            '#ffffff',
        'on-tertiary-container':  '#20bf86',
        'tertiary-fixed':         '#6ffbbe',
        'tertiary-fixed-dim':     '#4edea3',
        'surface':                '#f8f9fb',
        'surface-bright':         '#f8f9fb',
        'surface-dim':            '#d9dadc',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f3f4f6',
        'surface-container':         '#edeef0',
        'surface-container-high':    '#e7e8ea',
        'surface-container-highest': '#e1e2e4',
        'surface-variant':        '#e1e2e4',
        'on-surface':             '#191c1e',
        'on-surface-variant':     '#434750',
        'inverse-surface':        '#2e3132',
        'inverse-on-surface':     '#f0f1f3',
        'inverse-primary':        '#aec6ff',
        'outline':                '#747782',
        'outline-variant':        '#c4c6d2',
        'background':             '#f8f9fb',
        'on-background':          '#191c1e',
        'error':                  '#ba1a1a',
        'error-container':        '#ffdad6',
        'on-error':               '#ffffff',
        'on-error-container':     '#93000a',
        'surface-tint':           '#395da1',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter': '16px',
        'lg': '24px',
        'margin-mobile': '16px',
        'sm': '8px',
        'margin-desktop': '32px',
        'md': '16px',
        'base': '4px',
        'xl': '32px',
        'xs': '4px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-sm':   ['11px', { lineHeight: '14px', fontWeight: '600' }],
        'label-md':   ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-sm':    ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md':    ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-lg':   ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-sm':['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md':['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      keyframes: {
        'pulse-dot': {
          '0%':   { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(32,191,134,0.7)' },
          '70%':  { transform: 'scale(1)',    boxShadow: '0 0 0 6px rgba(32,191,134,0)' },
          '100%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(32,191,134,0)' },
        },
      },
      animation: {
        'pulse-dot': 'pulse-dot 2s infinite',
      },
    },
  },
  plugins: [],
}
